include::header.adoc[]
include::../dates.adoc[]

:title: Assignment 2: C what you can do
:Author Initials: ASN
:Date:    2021-01-29
:Revision: 0.1
:ASST: A02

= {title}

**Due {ASST02_DUE}, before midnight**

The goals for this assignment are:

* Work with binary numbers
* Work with C structs, strings, and arrays

[discrete]
= Update your repository

We will use the same repository as link:asst01.html[Assignment 1]

Pull to get the assignment basecode.

[source, subs="attributes,quotes"]
----
$ cd {repo}
$ git pull 
----

Your repository should now contain a new folder named `{ASST}`.

:sectnums:
= Integers 

Write a program, `integer.c`, that outputs an integer in binary using two's compliment.

[source,subs="quotes"]
----
$ **make integer**
gcc integer.c -o integer

$ **./integer 3** 
0000 0011

$ **./integer -1**
1111 1111
----

Requirements:

* Your program must use command line arguments to enter the value.
* You can assume all values can be represented with 1 byte.
* Match the output formatting

= Chips



= Subtext

Write a program, `decode.c`, that reads a binary file containing a sequence of characters. 
The first 4 bytes of the file store the number N of characters in the file. The remaining N 
bytes of the file correspond to a character as follows:

* The highest order bit of each bytes combines into a secret message, terminated with `\0`. 
* The lower order 7 bits correspond to standard ASCII characters. 

For example, suppose the file is as follows (visualized using hexedit).

[discrete]
= Submit your Work

Push you work to Github to submit your work.

[source, subs="attributes"]
----
$ cd {ASST}
$ git add *.c 
$ git commit -m "{ASST} complete"
$ git push
----

[discrete]
= Grading Rubric

*Assignment rubrics*

Grades are out of 4 points.

* (1 point) integer
** (0.1 points) style 
** (0.4 points) correct behavior: asks the user for input and creates the new string
** (0.5 points) no memory errors
* (2 point) logical_ops 
** (0.1 points) style 
** (0.9 points) correct behavior: asks the user for input and creates the new string
** (1.0 points) no memory errors
* (1 points) bitmap
** (0.1 points) style 
** (0.4 points) correct behavior
** (0.5 points) no memory errors

*Code rubrics*

For full credit, your C programs must be feature-complete, robust (e.g. run without memory errors or crashing) and 
have good style.

* Some credit lost for missing features or bugs, depending on severity of error
* -12.5% for style errors. See the link:../codingstandard.html[class coding style] here.
* -50% for memory errors
* -100% for failure to checkin work to Github
* -100% for failure to compile on linux using make
